name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        # run: npm run build
        run: npm run build && cp ./dist/index.html ./dist/404.html
        # https://github.com/vyonizr/react-vite-gh-pages/
        # There is a GitHub’s 404 error when we refresh the page on children path relative to the basename route
        # It is recommended to use npm or yarn as the package manager and has 
        # its package-lock.json or yarn.lock lockfile present in the repository.
        # GitHub Actions does not support pnpm’s pnpm-lock.yaml at the moment of this writing.

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist